### PR TITLE
Typo fix in the mysql schema creation command

### PR DESCRIPTION
**Pull request by RosemaryOrchard**
Missing space

### CODE REVIEW

**Comment by aaronpk** [comment]
what version of mysql are you using? I guess I haven't actually tried with the space in a while, but it used to only work with no space.

**Comment by RosemaryOrchard** [comment]
I use 5.7 and referenced this page today (for other purposes) to double check: https://dev.mysql.com/doc/refman/5.5/en/time-zone-support.html

**Comment by Lewiscowles1986** [comment]
I can confirm adding a space is not how any MySQL script I've ever written works, but perhaps uri database connection string would help?

**Comment by Lewiscowles1986** [comment]
https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html

**Comment by Ruxton** [comment]
This fix is correct `-pownyourgram` sends the password as ownyourgarm `-p ownyourgram` is setting the database to ownyourgra.

**Pull request closed without merging**
